title = "Dreaming Spires"

[params]
fathom_id = "testvalue"
company_number = 13902798
company_name = "Dreaming Spires Software Development Ltd"

[params.nav]
navbar = [
    { url = "/", name = "Home" },
    { url = "/portfolio", name = "Our Projects" },
    { url = "/our_clients", name = "Our Clients" },
    { url = "/careers", name = "Careers" }
]

hotlinks = [
    { url = "/contact", name = "Contact Us" }
]

footer = [
    { url = "/", name = "Home" },
    { url = "/portfolio", name = "Our Projects" },
    { url = "/our_clients", name = "Our Clients" },
    { url = "/careers", name = "Careers" },
    { url = "/contact", name = "Contact" },
    { url = "/privacy_policy", name = "Privacy Policy" }
]

[permalinks]
# TODO: fix the portfolio links not working
"/portfolio/" = "/portfolio/{{ .Date.Format `2006/01/02` }}/{{ path.Base .Path }}/"

[[tasks]]
input = [".md", ".html"]
output = ".html"
template = ".html"
preprocess.md = "mdtohtml -u"
static_dir = "static"
output_dir = "public"

[[tasks.feeds]]
input_dir = "portfolio"
title = "Dreaming Spires blog"
template = "atom.xml"
output = "portfolio/atom.xml"

[[tasks]]
input = [".scss"]
output = ".css"
preprocess.scss = "npx sass --stdin"
output_dir = "public/assets"
ugly_urls = true

[[tasks]]
input = [".jpg", ".jpeg", ".png"]
output = ".jpg"
preprocess.jpg = "magick /dev/stdin -strip -interlace Plane -gaussian-blur 0.05 -quality 85% /dev/stdout"
output_dir = "public"
ugly_urls = true
